---
baseurl: "http://fzero.rubi.gd/"
title: "یادداشتهای بیت نیمسوز"
permalinks:
  post: /:year/:month/:slug/
params:
  Subtitle: "یک وبلاگ دیگر از یک برنامه نویس دیگر"
  AuthorName: "fzerorubigd"
  disqusShortname: fzerorubigd
  github: "fzerorubigd"
  twitter: "fzerorubigd"
  footerNote: Copyleft fzerorubigd
  top_menu:
    - Title: وبلاگ قدیمی
      Link: http://cyberrabbits.net
    - Title: توییتر
      Link: https://twitter.com/fzerorubigd
---
